import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { accessSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));
const generatedMarker = 'Generated by DesignKernel';
const config = JSON.parse(
  await readFile(path.join(root, 'designkernel.config.json'), 'utf8'),
);
const projectRoot = path.resolve(root, config.projectRoot);
const relation = path.relative(root, projectRoot);

if (relation.startsWith('..') || path.isAbsolute(relation)) {
  throw new Error(`Configured projectRoot escapes the repository: ${config.projectRoot}`);
}

function exists(filePath) {
  try {
    accessSync(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function syncFile(destination, content) {
  await mkdir(path.dirname(destination), { recursive: true });
  const destinationExists = exists(destination);

  if (destinationExists) {
    const current = await readFile(destination, 'utf8');
    if (current === content) {
      console.log(`UNCHANGED ${path.relative(root, destination)}`);
      return true;
    }
    if (!current.includes(generatedMarker)) {
      console.warn(`PROTECTED ${path.relative(root, destination)} (not generated by DesignKernel)`);
      return false;
    }
  }

  await writeFile(destination, content, 'utf8');
  console.log(`${destinationExists ? 'SYNCED' : 'CREATED'} ${path.relative(root, destination)}`);
  return true;
}

function generatedHeader(source) {
  return `<!-- ${generatedMarker}. Source: ${source}. Do not edit; run pnpm design:sync. -->\n\n`;
}

const directorSource = 'atelierOS/kernel/design-director/SKILL.md';
const reviewerSource = 'atelierOS/kernel/design-reviewer/SKILL.md';
const director = await readFile(path.join(root, directorSource), 'utf8');
const reviewer = await readFile(path.join(root, reviewerSource), 'utf8');

const results = [];
results.push(
  await syncFile(
    path.join(projectRoot, '.agents/skills/design-director/SKILL.md'),
    generatedHeader(directorSource) + director,
  ),
);
results.push(
  await syncFile(
    path.join(projectRoot, '.agents/skills/design-reviewer/SKILL.md'),
    generatedHeader(reviewerSource) + reviewer,
  ),
);

const integrations = {
  codex: {
    destination: '.codex/designkernel.md',
    content: `${generatedHeader(directorSource)}# DesignKernel for Codex\n\nFor substantial frontend work, read repository-root \`AGENTS.md\`, then use \`atelierOS/kernel/design-director/SKILL.md\`. Read \`src/PRODUCT.md\`, \`src/DESIGN.md\`, and relevant \`src/.design/\` memory before selecting a profile, workflow, and installed engines. Apply \`atelierOS/kernel/design-reviewer/SKILL.md\` before completion.\n`,
  },
  cursor: {
    destination: '.cursor/rules/designkernel.mdc',
    content: `---\ndescription: Route substantial frontend work through DesignKernel\nalwaysApply: true\n---\n\n<!-- ${generatedMarker}. Source: ${directorSource}. Do not edit; run pnpm design:sync. -->\n\nRead repository-root \`AGENTS.md\` and use \`atelierOS/kernel/design-director/SKILL.md\` for substantial frontend work. Read src product/design memory, select the relevant profile and workflow, use only appropriate installed engines, and review major UI work before completion.\n`,
  },
  claude: {
    destination: '.claude/commands/designkernel.md',
    content: `${generatedHeader(directorSource)}Use the DesignKernel Design Director at repository-root \`atelierOS/kernel/design-director/SKILL.md\` for this frontend task. Read \`src/PRODUCT.md\`, \`src/DESIGN.md\`, and relevant \`src/.design/\` memory; select the profile, workflow, and appropriate installed engines; then apply \`atelierOS/kernel/design-reviewer/SKILL.md\` before completion.\n`,
  },
  copilot: {
    destination: '.github/instructions/designkernel.instructions.md',
    content: `---\napplyTo: "src/src/**/*.{js,jsx,ts,tsx,css,scss,html,vue,svelte}"\n---\n\n<!-- ${generatedMarker}. Source: ${directorSource}. Do not edit; run pnpm design:sync. -->\n\nFollow repository-root \`AGENTS.md\` and \`atelierOS/kernel/design-director/SKILL.md\` for substantial frontend work. Read src product/design memory, choose the relevant profile and workflow, and review major UI work with \`atelierOS/kernel/design-reviewer/SKILL.md\`.\n`,
  },
};

for (const [agent, integration] of Object.entries(integrations)) {
  if (!config.agents?.[agent]) {
    console.log(`DISABLED ${agent} adapter`);
    continue;
  }
  results.push(
    await syncFile(path.join(projectRoot, integration.destination), integration.content),
  );
}

if (results.some((result) => !result)) {
  console.error('\nSync stopped at protected files. Move or explicitly remove those files before retrying.');
  process.exitCode = 1;
} else {
  console.log('\nDesignKernel agent integrations are synchronized.');
}
